version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        SA_PASSWORD: "Pef@1234"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"
    ports:
        - "1433:1433"
    volumes:
        -   "F:\\docker\\sql:/var/opt/mssql/data"